# Generated by Django 3.2.2 on 2021-05-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
