# Generated by Django 3.2.2 on 2021-05-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210516_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
