# Generated by Django 3.2.2 on 2021-05-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_update_at_project_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='column_id',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='project_id',
            new_name='project',
        ),
    ]
