# Generated by Django 3.2.2 on 2021-05-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210516_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
